/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate three persona-conditioned drafts
         * @description Synchronous draft generation. Returns 2 drafts for Gratitude posts
         *     (Action-oriented auto-pruned) and 3 otherwise.
         *
         *     Pipeline (server-side):
         *     1. Input safety filter (crisis lexicon).
         *     2. Memory retrieval — chronological + activity-type from
         *        `memory.sqlite` for this `(participant_id, cohort_id)`.
         *     3. Engagement fingerprint — read panel.parquet via the dropout
         *        sister service or local mount; emit one-line summary.
         *     4. Three independent decodes from the fine-tuned SLM with style
         *        suffixes + cross-draft n-gram blocking.
         *     5. MI-policy post-filter — regenerate any draft that violates
         *        HOPE rule 4 (ask-before-advise).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GenerateRequest"];
                };
            };
            responses: {
                /** @description Drafts generated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GenerateResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Write a participant post to memory (idempotent)
         * @description Called by the HOPE MOVE platform webhook on every new participant
         *     post, OR by the JSON-reconcile cron during catch-up. Idempotent on
         *     `activity_id` — replays are safe.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MemoryPostRequest"];
                };
            };
            responses: {
                /** @description Stored or deduped. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoryWriteResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Write a facilitator reply to memory (idempotent)
         * @description Called by the HOPE MOVE platform webhook when a facilitator replies
         *     via the platform's own UI (not via our dashboard — those replies
         *     are written directly via the HITL fast-path on `/event`).
         *     Idempotent on `comment_id`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MemoryReplyRequest"];
                };
            };
            responses: {
                /** @description Stored or deduped. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoryWriteResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk write — used for reconciliation and one-off backfill */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MemoryBatchRequest"];
                };
            };
            responses: {
                /** @description Batch processed; counts and per-item errors returned. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoryBatchResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/post/{activity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Right-to-erasure — hard delete a post and its associated reply rows */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    activity_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "deleted";
                            rows_affected: number;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/{participant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Debug — show what the retriever sees for a participant
         * @description Admin / debug only. Returns the rows the chronological retriever would surface for the given participant within the given cohort.
         */
        get: {
            parameters: {
                query?: {
                    cohort_id?: number;
                    limit?: number;
                };
                header?: never;
                path: {
                    participant_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Memory entries. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoryEntry"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/thumb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Capture facilitator thumbs-up/down on a draft
         * @description Independent of any send action. A facilitator may thumbs-up a draft
         *     they did not pick this time (signal: "good draft, not the one I
         *     needed today") or thumbs-down a draft they edited and sent. This is
         *     the high-value KTO unary signal.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ThumbRequest"];
                };
            };
            responses: {
                /** @description Thumb recorded. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AckResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Final action on a draft set (accept / edit / reject / flag)
         * @description Records the facilitator's eventual decision against a draft set.
         *     Side effect for action ∈ {accept, edit}: the `sent_text` is written
         *     to memory via the HITL fast-path so subsequent `/generate` calls
         *     see it within milliseconds (without waiting for the platform
         *     webhook). Edit distance to the chosen draft body is computed and
         *     stored on the matching `hitl_drafts` row.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EventRequest"];
                };
            };
            responses: {
                /** @description Event recorded; memory updated when applicable. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AckResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/backfill-from-json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * One-off bootstrap from `data/UserActivity.txt` exports
         * @description Replays the JSON exports through `/memory/batch` internally.
         *     Idempotent. Run once at deploy time, or to recover after a memory
         *     DB rebuild. Returns the same shape as `/memory/batch`.
         */
        post: {
            parameters: {
                query?: {
                    /** @description Restrict backfill to a single cohort (e.g. 1680 for IIH demo). */
                    cohort_id?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Backfill complete. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoryBatchResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check (no auth) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service status. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service + model version (no auth) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Version info. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VersionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus scrape endpoint
         * @description Standard Prometheus exposition format. Latency histograms, error counts, cohort-size gauges.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prometheus metrics. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Hope Programme activity taxonomy.
         * @enum {string}
         */
        ActivityType: "GoalSetting" | "Gratitude" | "MyHOPE";
        /**
         * @description Draft style. Locked by the dashboard contract at
         *     `dropout_ml_v2/deploy/dashboard/app.py:79-107`.
         * @enum {string}
         */
        Persona: "Empathetic" | "Action-oriented" | "Goal-oriented";
        /**
         * @description Display label paired with `Persona`. Locked by dashboard contract.
         * @enum {string}
         */
        PersonaLabel: "Warm personal check-in" | "Small next-step nudge" | "Goal-focused support";
        /**
         * @description Optional engagement-fingerprint inputs. **Weekly cadence** — the
         *     `dropout_ml_v2` model recomputes scores once per week per
         *     (participant, week_number); see their README §"Cold-start handling
         *     and inference contract". The dashboard caches scores for the week
         *     and re-evaluates at week boundaries. Fields here may therefore be
         *     up to ~7 days stale relative to the current post — by design.
         *
         *     Sourced from
         *     `dropout_ml_v2/outputs/artifacts/cumulative_features_panel.parquet`
         *     (weekly snapshot) or computed at the next week boundary by their
         *     `:8000/predict` call. When present, a one-line natural-language
         *     summary is injected into the draft prompt.
         *
         *     Stale-by-design contrast: the memory store (participant writing
         *     history) is hydrated in real-time via webhook on every new post,
         *     while the dropout fingerprint is intentionally weekly. The two
         *     signals coexist with different freshness characteristics.
         */
        EngagementSignals: {
            /** Format: float */
            days_since_last_login?: number;
            /** Format: float */
            days_since_last_activity?: number;
            /** Format: float */
            current_inactive_streak?: number;
            /** Format: float */
            engagement_slope?: number;
            /** Format: float */
            engagement_intensity?: number;
            cum_login_count?: number;
            cum_activity_count?: number;
            cum_unique_pages?: number;
            /** @enum {integer} */
            wrote_first_week_binary?: 0 | 1;
            /** @enum {integer} */
            received_comment_first_week_binary?: 0 | 1;
            /** Format: float */
            dropout_risk?: number;
            /** @enum {string} */
            risk_level?: "low" | "medium" | "high";
        };
        /**
         * @description Request body for `POST /generate`. Two callers expected:
         *
         *     1. **`dropout_ml_v2` Streamlit dashboard** (legacy contract) — sends
         *        the narrow `LegacyGenerateRequest` shape with `display_name`,
         *        `module_id`, `week_number`, and three engagement fields. We
         *        generate stub-equivalent drafts when the actual post text is
         *        unavailable.
         *     2. **`hope-dashboard` Next.js app** (rich contract) — sends
         *        `participant_id`, `cohort_id`, `activity_id`, `activity_type`,
         *        and `post_text` for full memory-augmented generation.
         *
         *     Both shapes accepted via additive optional fields; server picks the
         *     richer path when `post_text` is present.
         */
        GenerateRequest: components["schemas"]["RichGenerateRequest"] | components["schemas"]["LegacyGenerateRequest"];
        RichGenerateRequest: {
            /** @description Platform user_id. */
            participant_id: number;
            /** @description Platform cohort.id (e.g. 1680 for IIH-COH12-110226). */
            cohort_id: number;
            /** @description Platform module.id (e.g. 337 for IIH 2025 V1). */
            module_id?: number;
            activity_id?: number;
            activity_type?: components["schemas"]["ActivityType"];
            post_text: string;
            /** @description Used in the Empathetic-style lead-in. */
            display_name?: string;
            engagement?: components["schemas"]["EngagementSignals"];
        };
        /**
         * @description Verbatim shape from `dropout_ml_v2/deploy/dashboard/app.py:619-626`.
         *     Kept for backward compatibility — do not break.
         */
        LegacyGenerateRequest: {
            display_name: string;
            module_id: number;
            week_number: number;
            /** Format: float */
            dropout_risk?: number;
            /** Format: float */
            current_inactive_streak?: number;
            /** @enum {integer} */
            wrote_first_week_binary?: 0 | 1;
        };
        Draft: {
            persona: components["schemas"]["Persona"];
            label: components["schemas"]["PersonaLabel"];
            /** @description 1–2 sentence draft. Single facilitator turn. */
            body: string;
            /**
             * Format: uuid
             * @description Quote on subsequent `/thumb` and `/event` calls.
             */
            draft_id: string;
            /** @description Optional MI-scorer per-draft summary (debug). */
            mi_signature?: {
                /** Format: float */
                open_question_ratio?: number;
                /** Format: float */
                reflection_density?: number;
                /** Format: float */
                prescriptive_density?: number;
            };
        };
        GenerateResponse: {
            /**
             * @description Three drafts in non-Gratitude activity types; two on Gratitude
             *     posts (Action-oriented dropped — HOPE manual rule "on a
             *     gratitude post you may simply acknowledge").
             */
            drafts: components["schemas"]["Draft"][];
            /**
             * Format: uuid
             * @description Links the drafts; quote on `/event`.
             */
            draft_set_id: string;
            /** @description false on cold-start (no prior posts for this participant). */
            memory_used?: boolean;
            /** @description false when no engagement signals provided. */
            engagement_used?: boolean;
            /**
             * @description Set when input safety filter blocks the post (crisis lexicon
             *     match). Drafts array is empty; client should render the
             *     signposting message instead.
             */
            safety_signposting?: string | null;
            /** @example finetuned_slm_Qwen2.5-1.5B_hope-only */
            model_version?: string;
            /** Format: date-time */
            generated_at: string;
        };
        /** @enum {string} */
        MemoryRole: "participant_post" | "facilitator_reply";
        /** @enum {string} */
        MemorySource: "platform_webhook" | "platform_backfill" | "json_reconcile" | "hitl";
        MemoryPostRequest: {
            /** @description Idempotency key (combined with role=participant_post). */
            activity_id: number;
            participant_id: number;
            cohort_id: number;
            module_id: number;
            activity_type?: components["schemas"]["ActivityType"];
            text: string;
            /** Format: date-time */
            recorded_at: string;
            display_name?: string | null;
            source: components["schemas"]["MemorySource"];
        };
        MemoryReplyRequest: {
            /** @description Idempotency key (combined with role=facilitator_reply). */
            comment_id: number;
            /** @description The post being replied to. */
            activity_id: number;
            participant_id: number;
            cohort_id: number;
            facilitator_id: string;
            text: string;
            /** Format: date-time */
            recorded_at: string;
            source: components["schemas"]["MemorySource"];
        };
        MemoryWriteResponse: {
            /** @enum {string} */
            status: "stored" | "deduped";
            memory_id?: number;
        };
        MemoryBatchRequest: {
            items: ((components["schemas"]["MemoryPostRequest"] & {
                /** @constant */
                kind: "post";
            }) | (components["schemas"]["MemoryReplyRequest"] & {
                /** @constant */
                kind: "reply";
            }))[];
        };
        MemoryBatchResponse: {
            stored: number;
            deduped: number;
            errors: {
                index: number;
                reason: string;
            }[];
        };
        /** @description Row returned by debug `/memory/{participant_id}`. */
        MemoryEntry: {
            memory_id?: number;
            participant_id?: number;
            cohort_id?: number;
            /** Format: date-time */
            ts?: string;
            activity_id?: number | null;
            activity_type?: components["schemas"]["ActivityType"] | null;
            role?: components["schemas"]["MemoryRole"];
            text?: string;
        };
        ThumbRequest: {
            /** Format: uuid */
            draft_id: string;
            /** @enum {string} */
            label: "up" | "down";
            facilitator_id: string;
        };
        /** @enum {string} */
        EventAction: "accept" | "edit" | "reject" | "flag";
        EventRequest: {
            /** Format: uuid */
            draft_set_id: string;
            /**
             * Format: uuid
             * @description The draft variant the facilitator acted on. For action=accept or
             *     action=edit, the same persona's text is also written to memory
             *     via the HITL fast-path so subsequent /generate calls see it
             *     without waiting for the platform webhook.
             */
            chosen_draft_id: string;
            action: components["schemas"]["EventAction"];
            /**
             * @description Required when action ∈ {accept, edit}. Forbidden otherwise.
             *     For action=accept this should equal the draft body verbatim;
             *     for action=edit it is the facilitator's edited text.
             */
            sent_text?: string | null;
            facilitator_id: string;
            /** @description Required when action=flag. */
            flag_reason?: string | null;
        };
        AckResponse: {
            /** @enum {string} */
            status: "ok";
        };
        HealthResponse: {
            /** @enum {string} */
            status: "healthy" | "degraded";
            model_loaded?: boolean;
            /** @enum {string} */
            memory_db?: "ok" | "missing" | "error";
            /** @enum {string} */
            dropout_api?: "reachable" | "unreachable";
            /** Format: date-time */
            timestamp?: string;
        };
        VersionResponse: {
            /** @example 0.1.0 */
            service_version: string;
            /** @example finetuned_slm_Qwen2.5-1.5B_hope-only */
            model_version: string;
            /** Format: date-time */
            deployed_at: string;
            commit_sha?: string;
        };
        ErrorResponse: {
            detail: string;
            /** @example invalid_signature */
            code?: string;
        };
    };
    responses: {
        /** @description HMAC signature missing or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Validation error. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
